### PR TITLE
Add connect api endpoint

### PR DESCRIPTION
**Pull request by happyleavesaoc**
Support for the new Spotify Connect API: https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/

### CODE REVIEW

**Comment by tgurr** [comment]
As discussed in https://github.com/home-assistant/home-assistant/issues/7286 would it be possible to get this feature integerated and a new spotipy version released? This would ease adoption for distributions. Personally I can say I've tested spotipy (in combination with home assistant and different hardware, namely an Amazon FireTV and a Google Nexus 4 with the official Android Spotify app) with this pull request and it works really well so I'd love to see this feature getting merged.

**Comment by durzo** [comment]
I had to make a small fix to this PR in order to get it working.

_append_device_id adds "&device_id=%s" onto the path but this breaks if there are no existing query strings (missing "?"). causing spotify API to return 404

This fixed for me:
```
    def _append_device_id(self, path, device_id):
        ''' Append device ID to API path.

            Parameters:
                - device_id - device id to append
        '''
        if device_id:
            if '?' in path:
                path += "&device_id=%s" % device_id
            else:
                path += "?device=id=%s" % device_id
        return path
```

**Comment by jhaucke** [comment]
For those who wonder why changing the current device not working correctly:
With "?device_id=%s" instead of "?device=id=%s" it will work even better ;)

**Comment by happyleavesaoc** [comment]
@durzo @jhaucke updated PR with that fix.

**Comment by lenisko** [comment]
@plamere could you hit accept ;-) ?

**Comment by dirtshell** [comment]
Will accept tommorow. Very drunk right now. And can't figure things out right now.

**Comment by plamere** [comment]
Nice PR, thanks!

**Comment by happyleavesaoc** [comment]
Thanks for the merge!

**Pull request merged**
