### PR TITLE
Refactor client internal calls to allow keepalive

### PR DESCRIPTION
**Pull request by sonneveld**
Internal calls were closing the http connection after every request, which meant that subsequent queries had to recreate the connection. By only closing the request object, I halved the time it took to get my saved tracks:

loading saved tracks before:
real	0m39.799s

loading saved tracks after:
real	0m19.340s

### CODE REVIEW

**Comment by Harrison97** [comment]
Hey! I am hosting a new master branch for this repo since the old creator has been MIA for 2 years. Hoping to get this repo back on it's feet and in good standing. I've been working on updating tests and adding all new functionality and have merged some of the PR's that I thought were sufficient for merging. If your PR didn't make it, resubmit it please.

Thanks!

https://github.com/Harrison97/spotipy

**Comment by stephanebruckert** [comment]
Hey @sonneveld. Great PR, thanks! Just ran the tests locally, and integration tests are twice as fast:

> Ran 60 tests in 8.069s

vs.

> Ran 60 tests in 17.863s

Going to resolve conflicts and merge it. Will open a new one to fix a warning in the tests

**Comment by stephanebruckert** [comment]
TIL we are allowed to push on a fork's branch if a PR is open:

> You can commit changes on a pull request branch that was created from a fork of your repository with permission from the pull request creator.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by sonneveld** [comment]
Nice! Just caught up on the news of the new maintainers. Good luck and thanks for taking it on.

**Pull request merged**
