### PR TITLE
 update user_playlists_contents.py

### PR DESCRIPTION
**Pull request by wesleybratt**
removed unused os import and unused variable 'top'

### CODE REVIEW

**Comment by wesleybratt** [comment]
honestly, its a little code cleanup but what I really want to see if this project is still being supported.

**Comment by gwynnebaer** [comment]
I'm still actively using the project. It's quite useful.

**Comment by wesleybratt** [comment]
Hey @gwynnebaer I'm still using this too... I wanted to see if active development and/or support was still happening by the creator/project owners.

**Comment by plamere** [comment]
thaks for the PR, - the project is indeed still active - but it is  a spare time project and sometimes life takes over. thanks for the nudge. And if anyone feels like they'd want to help out as an admin, I'd be up for that too.

**Comment by wesleybratt** [comment]
@plamere its easy to nudge, THANK YOU continuing to support it!

**Comment by wesleybratt** [comment]
@plamere this project is what got me started into learning python all of a few weeks ago. I'm happy to help go through some of the open issues and close out the ones that seem to be fixed.

**Pull request merged**
