### PR TITLE
Suppress warnings when cache path does not exist.

### PR DESCRIPTION
**Pull request by Peter-Schorn**
See issue #605 

I also changed the docs for `auth` parameter of `Spotify.init` to "access token" instead of "authorization token". In issue #599, a user confused the access token with the authorization code.

### CODE REVIEW

**Comment by Peter-Schorn** [comment]
It looks like the unit tests are failing because they expect `open` to be called with the cache path. You might have to help me fix the tests.

**Comment by stephanebruckert** [comment]
@Peter-Schorn to be honest I'm struggling with the tests as well, they would need a proper clean up.

Can I suggest we do it more simply: keep it like before but catch `FileNotFoundError`?

```
try:
    ..
except FileNotFoundError:
    ..
except IOError:
    ..
```

**Comment by Peter-Schorn** [comment]
@stephanebruckert I would've preferred to use `FileNotFoundError` as well, but it doesn't exist in python 2.7. That's why I had to change it to `os.path.exists`.

**Comment by Peter-Schorn** [comment]
I've been looking at the unit tests trying to figure out how they work, but I'm very confused. Is a cache file ever created for the tests?

**Comment by stephanebruckert** [comment]
It seems all mocked to me, checking that the right functions are called, and forcing their return values. It looks like we force the token to be created from a JSON. 

These tests might not be perfect or very clear, but I trust they make some sense. I would really avoid refactoring them in this PR. I'm having a look at the methods here to see if we could catch missing files in 2.7 https://stackoverflow.com/q/21367320/1515819

**Comment by stephanebruckert** [comment]
This would work in 2.7:

```python
import errno

try:
    open('./file')
except EnvironmentError as e:
    if e.errno == errno.ENOENT:
        print("File not found (file does not exist at all)")
    else:
        print("Can't read file (file exists, but might not have permission to read it")
```

**Comment by stephanebruckert** [comment]
Nice one! Looks great to me, I can merge if you want?

**Comment by Peter-Schorn** [comment]
Yes, go ahead.

**Pull request merged**
