### PR TITLE
docs: Use the print() function instead of the built-in

### LINKED ISSUE #329: Documentation examples use print builtin instead of function which is not python 3 compatible
The documentation (eg. https://github.com/plamere/spotipy/blob/master/docs/index.rst#welcome-to-spotipy). uses the built-in ```print``` statement instead of the ```print()``` function. This works for python2 but raises a syntax error on python3
```
print "Usage: %s username" % (sys.argv[0],)
                             ^
SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by toabctl**
This is compatible with python2 and python3 so the examples don't
throw a SyntaxError when trying them with python 3.

Closes #329

### CODE REVIEW

**Comment by Harrison97** [comment]
Hey! I am hosting a new master branch for this repo since the old creator has been MIA for 2 years. Hoping to get this repo back on it's feet and in good standing. I've been working on updating tests and adding all new functionality and have merged some of the PR's that I thought were sufficient for merging. If your PR didn't make it, resubmit it please.

Thanks!

https://github.com/Harrison97/spotipy

**Comment by toabctl** [comment]
@Harrison97 hey. do you have the permissions to upload to the pypi project, too? If not, I wonder if a rename of the project would make sense..

**Comment by Harrison97** [comment]
@toabctl I am in the process right now of getting access to the current name. If I can't then I will create a new name.

**Comment by toabctl** [comment]
I don't plan to work on this. Closing.

**Pull request closed without merging**
