### PR TITLE
'add to queue' endpoint added

### PR DESCRIPTION
**Pull request by Peter-Schorn**
see https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-add-to-queue

This is my first pull request, so please let me know if I've done anything wrong.

### CODE REVIEW

**Comment by stephanebruckert** [comment]
Thx for that, looks good!
To fix the lint you can do:

```
pip install autopep8
autopep8 --in-place --aggressive --recursive .
pip install flake8
flake8 .
```

**Comment by Peter-Schorn** [comment]
Ok, the lint should be fixed.

**Comment by Peter-Schorn** [comment]
How do I do that?

**Comment by stephanebruckert** [comment]
Yeah sorry the contributing instructions are missing.

This file would need a short line to explain what was added https://github.com/plamere/spotipy/blob/master/CHANGELOG.md. You can add it in "unreleased".

**Comment by Peter-Schorn** [comment]
Ok, I added it to the changelog

**Comment by stephanebruckert** [comment]
Thanks! Merged

**Pull request merged**
