### PR TITLE
Implement get-queue endpoint

### LINKED ISSUE #853: Implement get-queue endpoint
I would like to request the current queue for a user. Spotify recently implemented this in their web API: https://developer.spotify.com/console/get-queue/

Also see [this thread](https://community.spotify.com/t5/Live-Ideas/Developer-Web-API-playback-queue-route/idi-p/5202433/page/3#comments).

### PR DESCRIPTION
**Pull request by JobDoesburg**
Implements [Spotify's get queue endpoint](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-queue)

Closes #853

### CODE REVIEW

**Review by stephanebruckert — APPROVED** [review]

**Comment by stephanebruckert** [comment]
@JobDoesburg I just tried to write a test for it but I'm getting a 403 even though I included the scope `user-read-currently-playing`

```
def test_get_queue(self):
    res = self.spotify.get_queue()
```

```
======================================================================
ERROR: test_get_queue (integration.user_endpoints.test.SpotipyPlayerApiTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbr/projects/spotipy/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/me/player/queue

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sbr/projects/spotipy/tests/integration/user_endpoints/test.py", line 507, in test_get_queue
    res = self.spotify.get_queue()
  File "/Users/sbr/projects/spotipy/spotipy/client.py", line 1877, in get_queue
    return self._get("me/player/queue")
  File "/Users/sbr/projects/spotipy/spotipy/client.py", line 297, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/Users/sbr/projects/spotipy/spotipy/client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/player/queue:
 Forbidden., reason: None
```

any idea? did you make it work?

**Comment by JobDoesburg** [comment]
Hi, sorry I didn't respond, it got buried in my todo list. I see you got it working already by adding a new scope, right? Let me know if there are still problems and I will dive into it :)

**Comment by stephanebruckert** [comment]
No, the github checks don't run the integration tests, only units. 
I believe the endpoint does not work but would be curious to know if you can make it work somehow. Thanks!

**Comment by JobDoesburg** [comment]
I have tried it and for me it works with no problems...

```python 
    def test_get_queue(self):
        res = self.spotify.get_queue()
        self.assertTrue('currently_playing' in res.keys() and 'queue' in res.keys())
```

The result of `get_queue()` is `{'currently_playing': None, 'queue': []}` when nothing is playing or `{'currently_playing': {'alum': ... }, 'queue': [{...}, {...}, ...]}` when something is playing.

I'm using the same scope `user-read-playback-state` so I cannot really reproduce the error myself...

**Comment by stephanebruckert** [comment]
@JobDoesburg ok thanks that put me in the right direction! I figured it works for premium users only, which makes writing a test for it not really possible (test user on CI is free). 

The only doc mentioning that could be this page https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/ if we assume that `me/player/queue` is part of the playback category of endpoints.

**Pull request merged**
