### PR TITLE
Implement retry handling for POST

### PR DESCRIPTION
**Pull request by hmhrex**

### CODE REVIEW

**Comment by Harrison97** [comment]
Hey! I am hosting a new master branch for this repo since the old creator has been MIA for 2 years. Hoping to get this repo back on it's feet and in good standing. I've been working on updating tests and adding all new functionality and have merged some of the PR's that I thought were sufficient for merging. If your PR didn't make it, resubmit it please.

Thanks!

https://github.com/Harrison97/spotipy

**Comment by stephanebruckert** [comment]
Hi @hmhrex, thanks for that. 2 years later, the package is maintained again. I know that's a late answer but is there a chance you can give this a new look and fix conflicts?

**Comment by hmhrex** [comment]
Sure! I’ll take a look at this this week. Glad it’s back!

**Comment by stephanebruckert** [comment]
Thanks a lot @hmhrex for your earlier efforts on this but I'm going to close it in favor of https://github.com/plamere/spotipy/pull/457 which uses `urllib3.Retry`

**Pull request closed without merging**
