### PR TITLE
List of tracks in a playlist added

### PR DESCRIPTION
**Pull request by CyanBook**
Get full details of the tracks of a playlist

Fixes https://github.com/plamere/spotipy/issues/335, https://github.com/plamere/spotipy/issues/318

### CODE REVIEW

**Comment by CyanBook** [comment]
Then why you didn't merge that function into the library?

**Comment by stephanebruckert** [comment]
It's only been 5 days 😄 https://github.com/plamere/spotipy/issues/387#issuecomment-573343444

I know the CI/CD is not set up yet, but if you manage to add a test for the function you wrote, that would be really helpful. Cheers

**Comment by CyanBook** [comment]
`{
  "href": "https://api.spotify.com/v1/playlists/0oY521mrfF81N8UZ0uzKA3/tracks?offset=0&limit=10",
  "items": [
    {
      "added_at": "2019-11-30T12:20:01Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/lorenzo.delmonte05"
        },
        "href": "https://api.spotify.com/v1/users/lorenzo.delmonte05",
        "id": "lorenzo.delmonte05",
        "type": "user",
        "uri": "spotify:user:lorenzo.delmonte05"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/215ciYy7TIYnGRim0I1nJ3"
              },
              "href": "https://api.spotify.com/v1/artists/215ciYy7TIYnGRim0I1nJ3",
              "id": "215ciYy7TIYnGRim0I1nJ3",
              "name": "JUNIOR CALLY",
              "type": "artist",
              "uri": "spotify:artist:215ciYy7TIYnGRim0I1nJ3"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1mvjZ7IEcOmWJ8M8DhiCOa"
          },
          "href": "https://api.spotify.com/v1/albums/1mvjZ7IEcOmWJ8M8DhiCOa",
          "id": "1mvjZ7IEcOmWJ8M8DhiCOa",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/8b9fee87463a6a122858afb8accf89255ba31b57",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/de478302e4f8a019b7151c1d11bea93cccaa1e1a",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/20f79c3bfbc60d98ac95fe5f6b531096f62a8474",
              "width": 64
            }
          ],
          "name": "Ricercato",
          "release_date": "2019-09-06",
          "release_date_precision": "day",
          "total_tracks": 12,
          "type": "album",
          "uri": "spotify:album:1mvjZ7IEcOmWJ8M8DhiCOa"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/215ciYy7TIYnGRim0I1nJ3"
            },
            "href": "https://api.spotify.com/v1/artists/215ciYy7TIYnGRim0I1nJ3",
            "id": "215ciYy7TIYnGRim0I1nJ3",
            "name": "JUNIOR CALLY",
            "type": "artist",
            "uri": "spotify:artist:215ciYy7TIYnGRim0I1nJ3"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 159955,
        "episode": false,
        "explicit": true,
        "external_ids": {
          "isrc": "ITB001900423"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2AvB9xLqlKEPdCn14nXfBO"
        },
        "href": "https://api.spotify.com/v1/tracks/2AvB9xLqlKEPdCn14nXfBO",
        "id": "2AvB9xLqlKEPdCn14nXfBO",
        "is_local": false,
        "name": "Tutti con me",
        "popularity": 56,
        "preview_url": "https://p.scdn.co/mp3-preview/6b65fcd8bb665554dd89f2c91f225085bdc29e55?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:2AvB9xLqlKEPdCn14nXfBO"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2019-11-30T12:20:19Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/lorenzo.delmonte05"
        },
        "href": "https://api.spotify.com/v1/users/lorenzo.delmonte05",
        "id": "lorenzo.delmonte05",
        "type": "user",
        "uri": "spotify:user:lorenzo.delmonte05"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0lAWpj5szCSwM4rUMHYmrr"
              },
              "href": "https://api.spotify.com/v1/artists/0lAWpj5szCSwM4rUMHYmrr",
              "id": "0lAWpj5szCSwM4rUMHYmrr",
              "name": "Måneskin",
              "type": "artist",
              "uri": "spotify:artist:0lAWpj5szCSwM4rUMHYmrr"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/44a7Wk3Jh2JGVhjcFYWozj"
          },
          "href": "https://api.spotify.com/v1/albums/44a7Wk3Jh2JGVhjcFYWozj",
          "id": "44a7Wk3Jh2JGVhjcFYWozj",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273dbc892b8194e35ca3524e767",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02dbc892b8194e35ca3524e767",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851dbc892b8194e35ca3524e767",
              "width": 64
            }
          ],
          "name": "Il ballo della vita",
          "release_date": "2018-10-26",
          "release_date_precision": "day",
          "total_tracks": 12,
          "type": "album",
          "uri": "spotify:album:44a7Wk3Jh2JGVhjcFYWozj"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0lAWpj5szCSwM4rUMHYmrr"
            },
            "href": "https://api.spotify.com/v1/artists/0lAWpj5szCSwM4rUMHYmrr",
            "id": "0lAWpj5szCSwM4rUMHYmrr",
            "name": "Måneskin",
            "type": "artist",
            "uri": "spotify:artist:0lAWpj5szCSwM4rUMHYmrr"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 126706,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "ITB001800484"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/36ONZ2CvV8KsLPapNPGTqa"
        },
        "href": "https://api.spotify.com/v1/tracks/36ONZ2CvV8KsLPapNPGTqa",
        "id": "36ONZ2CvV8KsLPapNPGTqa",
        "is_local": false,
        "name": "L'altra dimensione",
        "popularity": 62,
        "preview_url": "https://p.scdn.co/mp3-preview/73ed672011c4998da1c8a8a5a160c9932e003967?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:36ONZ2CvV8KsLPapNPGTqa"
      },
      "video_thumbnail": {
        "url": null
      }
    }
  ],
  "limit": 10,
  "next": null,
  "offset": 0,
  "previous": null,
  "total": 2
}`

**Comment by CyanBook** [comment]
https://pastebin.com/W1kJsmPU you can find a test of what the response looks (that playlist has only 2 tracks)

**Comment by stephanebruckert** [comment]
Passes python2 and python3:

```
python3 -m unittest discover -v tests
test_basic_user_profile (test_auth.AuthTestSpotipy) ... ok
test_categories (test_auth.AuthTestSpotipy) ... ok
test_category_playlists (test_auth.AuthTestSpotipy) ... ok
test_current_user (test_auth.AuthTestSpotipy) ... ok
test_current_user_follows (test_auth.AuthTestSpotipy) ... ok
test_current_user_playlists (test_auth.AuthTestSpotipy) ... ok
test_current_user_save_and_unsave_tracks (test_auth.AuthTestSpotipy) ... ok
test_current_user_saved_albums (test_auth.AuthTestSpotipy) ... ok
test_current_user_saved_tracks (test_auth.AuthTestSpotipy) ... ok
test_current_user_top_artists (test_auth.AuthTestSpotipy) ... ok
test_current_user_top_tracks (test_auth.AuthTestSpotipy) ... ok
test_deprecated_starred (test_auth.AuthTestSpotipy) ... spotipy/spotipy/client.py:407: DeprecationWarning: You should use `playlist(playlist_id)` instead
  DeprecationWarning)
ok
test_deprecated_user_playlis (test_auth.AuthTestSpotipy) ... spotipy/spotipy/client.py:424: DeprecationWarning: You should use `playlist_tracks(playlist_id)` instead
  DeprecationWarning)
ok
test_deprecated_user_playlist (test_auth.AuthTestSpotipy) ... ok
test_featured_releases (test_auth.AuthTestSpotipy) ... ok
test_me (test_auth.AuthTestSpotipy) ... ok
test_new_releases (test_auth.AuthTestSpotipy) ... ok
test_playlist (test_auth.AuthTestSpotipy) ... ok
test_playlist_tracks (test_auth.AuthTestSpotipy) ... ok
test_track_bad_id (test_auth.AuthTestSpotipy) ... ok
test_user_follows_and_unfollows_artist (test_auth.AuthTestSpotipy) ... ok
test_user_follows_and_unfollows_user (test_auth.AuthTestSpotipy) ... ok
test_user_playlist_follow (test_auth.AuthTestSpotipy) ... ok
test_user_playlist_ops (test_auth.AuthTestSpotipy) ... ok
test_user_playlist_tracks (test_auth.AuthTestSpotipy) ... ok
test_user_playlists (test_auth.AuthTestSpotipy) ... ok
test_audio_analysis (test_auth2.AuthTestSpotipy) ... ok
test_audio_features (test_auth2.AuthTestSpotipy) ... ok
test_audio_features_with_bad_track (test_auth2.AuthTestSpotipy) ... ok
test_recommendations (test_auth2.AuthTestSpotipy) ... ok
test_request_with_token (test_client_credentials.ClientCredentialsTestSpotipy) ... ok
test_badly_scoped_token_bails (test_oauth.OAuthCacheTest) ... ok
test_expired_token_refreshes (test_oauth.OAuthCacheTest) ... ok
test_gets_from_cache_path (test_oauth.OAuthCacheTest) ... ok
test_saves_to_cache_path (test_oauth.OAuthCacheTest) ... ok
test_get_authorize_url_does_not_show_dialog_by_default (test_oauth.TestSpotifyOAuth) ... ok
test_get_authorize_url_doesnt_pass_state_by_default (test_oauth.TestSpotifyOAuth) ... ok
test_get_authorize_url_passes_state_from_constructor (test_oauth.TestSpotifyOAuth) ... ok
test_get_authorize_url_passes_state_from_func_call (test_oauth.TestSpotifyOAuth) ... ok
test_get_authorize_url_shows_dialog_when_requested (test_oauth.TestSpotifyOAuth) ... ok
test_album_search (tests.TestSpotipy) ... ok
test_album_tracks (tests.TestSpotipy) ... ok
test_album_tracks_many (tests.TestSpotipy) ... ok
test_album_urn (tests.TestSpotipy) ... ok
test_albums (tests.TestSpotipy) ... ok
test_artist_albums (tests.TestSpotipy) ... ok
test_artist_related_artists (tests.TestSpotipy) ... ok
test_artist_search (tests.TestSpotipy) ... ok
test_artist_search_with_market (tests.TestSpotipy) ... ok
test_artist_top_tracks (tests.TestSpotipy) ... ok
test_artist_urn (tests.TestSpotipy) ... ok
test_artists (tests.TestSpotipy) ... ok
test_custom_requests_session (tests.TestSpotipy) ... ok
test_force_no_requests_session (tests.TestSpotipy) ... ok
test_search_timeout (tests.TestSpotipy) ... ok
test_track_bad_id (tests.TestSpotipy) ... ok
test_track_bad_urn (tests.TestSpotipy) ... ok
test_track_id (tests.TestSpotipy) ... ok
test_track_search (tests.TestSpotipy) ... ok
test_track_url (tests.TestSpotipy) ... ok
test_track_urn (tests.TestSpotipy) ... ok
test_tracks (tests.TestSpotipy) ... ok
test_unauthenticated_post_fails (tests.TestSpotipy) ... ok
test_user (tests.TestSpotipy) ... ok

----------------------------------------------------------------------
Ran 64 tests in 8.695s

OK
```

**Pull request merged**
